services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/wordpress.conf:/etc/nginx/conf.d/wordpress.conf
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  wordpress_data:
  db_data:


