version: '3.7'

services:
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        ports:
            - "443:443"
        networks:
            - inception
        restart: always
    wordpress:

volumes:
    nginx_data:

networks:
    inception:



