services:
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      # This now points to a specific directory on your host machine
      - /home/adrgutie/data/wordpress:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    volumes:
      # This also points to the same host directory
      - /home/adrgutie/data/wordpress:/var/www/html
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    volumes:
      # This now points to the database directory on your host machine
      - /home/adrgutie/data/mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      - inception

# We no longer need the top-level volumes key because we are using bind mounts
# (linking directly to host paths) instead of named volumes.

networks:
  inception:
    driver: bridge