services:
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - ./.env # This tells nginx to load the .env file
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    # This block translates the .env variables to what WordPress expects
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_SUBSCRIBER_USER: ${WP_SUBSCRIBER_USER}
      WP_SUBSCRIBER_PASS: ${WP_SUBSCRIBER_PASS}
      WP_SUBSCRIBER_EMAIL: ${WP_SUBSCRIBER_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    # This block passes the .env variables directly to the MariaDB script
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      - inception

volumes:
  wordpress_data:
  db_data:

networks:
  inception:
    driver: bridge