services:
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/adrgutie/data/www:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - wordpress
    restart: always
    networks:
      - docker-network

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - /home/adrgutie/data/www:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_SUBSCRIBER_USER: ${WP_SUBSCRIBER_USER}
      WP_SUBSCRIBER_PASS: ${WP_SUBSCRIBER_PASS}
      WP_SUBSCRIBER_EMAIL: ${WP_SUBSCRIBER_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - mariadb
    restart: always
    networks:
      - docker-network

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - /home/adrgutie/data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      - docker-network

volumes:
  wordpress_data:
  db_data:

networks:
  docker-network:
    name: docker-network
    driver: bridge