# FROM mariadb:10.5
# ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
# ENV MYSQL_DATABASE=${MYSQL_DATABASE}
# ENV MYSQL_USER=${MYSQL_USER}
# ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
FROM mariadb:10.5

# Optional: seed SQL (if needed)
# COPY ./init.sql /docker-entrypoint-initdb.d/
