# FROM wordpress:fpm-alpine

# EXPOSE 9000
FROM wordpress:php8.2-fpm

# Optional: copy custom themes, plugins, or config if needed
# COPY ./my-theme /var/www/html/wp-content/themes/my-theme

# Expose port only if accessed directly (usually accessed via nginx)
EXPOSE 9000
